language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - ishacker.net@gmail.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - cd docs # into /docs folder
  - gitbook install # install plugins
  - gitbook build

after_script:
  - cd _book
  - git init
  - git remote add origin https://${GH_REF}
  - git add .
  - git commit -m ":rocket:Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${CTF_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master

env:
  global: 
    - GH_REF: github.com/YUbuntu0109/CTFlag-book.git # 设置 github 地址
